---
all:
  vars:
    var1: xyz
  hosts:
    host1:
      host1_var: xyz
    host2:
    host3:
  children:
    host_group1:
      hosts:
        host1:
        host2:
    host_group2:
      hosts:
        host2:
        host3:
      vars:
        group_var1: xyz
