---
- name: Tailscale install and join
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
    - role: artis3n.tailscale
      vars:
        tailscale_up_skip: true
      tags:
        - never
        - only_install
    - role: artis3n.tailscale
      vars:
        state: absent
      tags:
        - never
        - uninstall
