---
- name: Firewall Configuration for Hosthatch vps
  hosts: private_network_hosts
  become: true
  gather_facts: true
  tasks:
    - name: Allow everything from private network
      community.general.ufw:
        rule: allow
        src: 192.168.10.0/24
