- name: Verify docker installation
  service:
    name: docker
    state: started
    enabled: yes

- name: Get docker-compose version 
  command: docker-compose --version 
  register: docker_compose_version_result 
  changed_when: false 
  ignore_errors: true

- name: Parse docker-compose version 
  set_fact:
    docker_compose_version: " {{ docker_compose_version_result.stdout | regex_search('(\\d+)') | first | trim }} "
  when: docker_compose_version_result is success

- name: Assert docker-compose major version is 2
  assert:
    that: 
      - docker_compose_version == ' 2 '
    fail_msg: "The installed docker-compose version ({{ docker_compose_version }}) is not 2.x"
  when: docker_compose_version_result is success 

- name: Create directories for Adguard configuration
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/adguard
    - /etc/adguard/conf

- name: Copy Adguard config 
  template:
    src: "AdGuardHome.yaml.j2"
    dest: /etc/adguard/conf/AdGuardHome.yaml

- name: Copy docker-compose file
  template:
    src: "docker-compose.yaml.j2"
    dest: /etc/adguard/docker-compose.yaml

- name: Start traefik container
  shell: docker-compose up -d{{' --force-recreate' if force_recreate_containers else ''}}
  args:
    chdir: /etc/adguard
  tags: adguard
