---
collections:
  - name: devsec.hardening
    version: 8.7.0
roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.go
    version: 1.1.0
  - name: geerlingguy.nodejs
    version: 6.1.1
  - name: undergreen.prometheus-node-exporter
    version: v1.5.1
  - name: robertdebock.fail2ban
    version: 5.0.3
