---
collections:
  - name: devsec.hardening
    version: 8.7.0
roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.go
    version: 1.1.0
  - name: geerlingguy.nodejs
    version: 6.1.1
  - name: geerlingguy.pip
    version: 2.2.0
  - name: geerlingguy.node_exporter
    version: 2.0.1
  - name: robertdebock.fail2ban
    version: 5.0.3
  - name: robertdebock.users
    version: 5.6.0
  - name: robertdebock.firewall
    version: 5.1.6
