---
collections:
  - name: devsec.hardening
    version: 10.1.0
  - name: ansible.utils
    version: 5.1.2
  - name: community.general
    version: 10.1.0
  - name: ansible.posix
    version: 2.0.0
  - name: kubernetes.core
    version: 5.0.0
  - name: idiv_biodiversity.systemd
    version: 0.1.0
roles:
  - name: geerlingguy.docker
    version: 7.4.3
  - name: geerlingguy.go
    version: 1.1.0
  - name: geerlingguy.nodejs
    version: 7.0.0
  - name: geerlingguy.pip
    version: 3.1.0
  - name: geerlingguy.node_exporter
    version: 2.1.0
  - name: robertdebock.fail2ban
    version: 5.0.5
  - name: robertdebock.users
    version: 6.1.5
  - name: robertdebock.firewall
    version: 5.2.2
  - name: robertdebock.hostname
    version: 3.1.10
  - name: robertdebock.bootstrap
    version: 7.0.3
  - name: ahuffman.resolv
    version: 1.3.2
  - name: mrlesmithjr.netplan
    version: v0.4.2
  - name: artis3n.tailscale
    version: v4.5.0
