---
collections:
  - name: devsec.hardening
    version: 8.7.0
roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.go
    version: 1.1.0
  - name: geerlingguy.nodejs
    version: 6.1.1
