---
collections:
  - name: devsec.hardening
    version: 8.7.0
  - name: ansible.utils
    version: 2.10.3
  - name: community.general
    version: 7.1.0
  - name: ansible.posix
    version: 1.5.4
  - name: kubernetes.core
    version: 2.4.0
roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.go
    version: 1.1.0
  - name: geerlingguy.nodejs
    version: 6.1.1
  - name: geerlingguy.pip
    version: 2.2.0
  - name: geerlingguy.node_exporter
    version: 2.0.1
  - name: robertdebock.fail2ban
    version: 5.0.3
  - name: robertdebock.users
    version: 5.6.0
  - name: robertdebock.firewall
    version: 5.1.6
  - name: robertdebock.hostname
    version: 3.1.7
  - name: robertdebock.bootstrap
    version: 6.1.6
  - name: ahuffman.resolv
    version: 1.3.2
  - name: mrlesmithjr.netplan
    version: v0.3.0
  - name: artis3n.tailscale
    version: v4.2.2
  - name: idiv_biodiversity.systemd_resolved
    src: https://github.com/idiv-biodiversity/ansible-role-systemd-resolved
    version: v1.2.0    
