---
- name: Setup default user accounts
  gather_facts: true
  hosts: coolify_hosts
  become: true
  vars:
    # geerlingguy.docker 
    docker_service_manage: true
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: true
    docker_compose_version: "v2.19.0"
    docker_compose_arch: "{{ ansible_architecture }}"
    docker_compose_path: /usr/bin/docker-compose
    docker_users:
      - coolify
    docker_packages:
      - "docker-{{ docker_edition }}"
      - "docker-{{ docker_edition }}-cli"
      - "docker-{{ docker_edition }}-rootless-extras"
    
    # robertdebock.users
    users_group_list:
      - name: users
      - name: docker
    users_user_list:
      - name: coolify
        comments: Coolify Robotic Account
        uid: 9999
        groups: users,docker
        cron_allow: yes
        sudo_options:
          - 'ALL=(ALL) NOPASSWD: /usr/bin/docker'
          - 'ALL=(ALL) NOPASSWD: /usr/bin/docker-compose'
        authorized_keys:
          - "https://gist.githubusercontent.com/sulo1337/8b2c5625e82d1c2898108147a3564073/raw/5211586c9e706cd01516da6e71b289e5933fa44b/coolify_pubkey.pub"
        expires: -1
        password_validity_days: 99999
  roles:
    - robertdebock.users
    - geerlingguy.docker