---
- name: Setup coolify server
  gather_facts: true
  hosts: coolify_server
  become: true
  vars:
    traefik_port_mappings:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
  tasks:
    - name: Allow everywhere from docker network
      community.general.ufw:
        rule: allow
        direction: in
        from_ip: "172.16.0.0/12"
    - name: Get IP address of tailscale network interface
      ansible.builtin.command: "tailscale ip -4"
      register: tailscale_ip
      changed_when: false
      check_mode: no
      ignore_errors: true
    - name: Create port mappings for tailscale ip
      set_fact:
        tailscale_port_mappings:
          - "{{ tailscale_ip.stdout }}:80:80"
          - "{{ tailscale_ip.stdout }}:443:443"
      when: tailscale_ip.rc == 0
    - name: Add port mappings to traefik_port_mappings
      set_fact:
        traefik_port_mappings: "{{ traefik_port_mappings + tailscale_port_mappings }}"
      when: tailscale_ip.rc == 0
    - name: Remove duplicate port mappings
      set_fact:
        traefik_port_mappings: "{{ traefik_port_mappings | unique }}"
    - name: Add 0.0.0.0 mappings if traefik_public is set
      set_fact:
        traefik_port_mappings:
          - "0.0.0.0:80:80"
          - "0.0.0.0:443:443"
      when: traefik_public is defined and traefik_public
    - name: Get cloudflare api token from environment
      ansible.builtin.set_fact:
        cloudflare_dns_api_token: "{{ lookup('env', 'CLOUDFLARE_DNS_API_TOKEN') }}"
      when: lookup('env', 'CLOUDFLARE_DNS_API_TOKEN') != ''
      no_log: true
    - name: Verify cloudflare api token is set
      fail:
        msg: "CLOUDFLARE_DNS_API_TOKEN is not set"
      when: cloudflare_dns_api_token is not defined
    - name: Setup traefik config
      template:
        src: "templates/traefik.yaml"
        dest: "/data/coolify/proxy/docker-compose.yml"
        owner: coolify
        group: coolify
        mode: '0644'
    - name: Create .env file for traefik
      copy:
        content: |
          CLOUDFLARE_DNS_API_TOKEN={{ cloudflare_dns_api_token }}
        dest: "/data/coolify/proxy/.env"
        owner: coolify
        group: coolify
        mode: '0640'
