---
- name: Loki deploy docker-compose
  hosts: loki_server
  gather_facts: true
  become: true
  vars:
    # loki specific vars
    loki_version: 2.8.3
    loki_traefik_network_name: traefik_tickernet_ansible_managed
    loki_fqdn: loki.tickerwolf.com
    loki_cert_resolver: dns
    # docker-compose-deploy specific vars
    docker_compose_template: "templates/docker-compose.yaml.j2"
    docker_compose_config_dir: /opt/ansible/docker-compose-apps/loki
    force_recreate_containers: false
    remove_volumes: false
    additional_templates: 
      - "templates/loki-config.yaml"
  roles:
    - role: docker-compose-deploy