---
- name: Check if public_key_path is defined
  stat:
    path: "{{ public_key_path | default('') }}"
  register: result

- name: Add SSH public key from file as authorized key for {{ username }}
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', public_key_path) }}"
  when: result.stat.exists

- name: Add SSH public key as authorized key for {{ username }}
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ public_key }}"
  when: not result.stat.exists and public_key is defined

- name: Fail when neither public_key nor public_key_path is provided
  fail:
    msg: "Error: Neither public_key nor public_key_path is provided"
  when: not result.stat.exists and public_key is undefined
