---
- name: Reboot hosts
  hosts: all
  tasks:
    - name: Reboot the host
      become: yes
      reboot:
        reboot_timeout: 600

    - name: Wait for host to be reachable
      wait_for_connection:
        timeout: 300