---
- name: Install Docker
  hosts: master
  gather_facts: true
  become: yes
  vars:
    # docker_compose_version is picked up from group vars and not managed here
    docker_edition: 'ce'
    docker_service_manage: true
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: true
    docker_compose_arch: "{{ ansible_architecture }}"
    docker_compose_path: /usr/local/bin/docker-compose
    docker_users:
      - tickerbot
    docker_packages:
      - "docker-{{ docker_edition }}"
      - "docker-{{ docker_edition }}-cli"
      - "docker-{{ docker_edition }}-rootless-extras"
  roles:
    - geerlingguy.docker
