  # meta:
  #   author: Sulochan Acharya
  #   description: This playbook will setup a gateway host with traefik that serves public/internal traffic
  #   usage: ansible-playbook -i <inventory> /path/to/install-traefik.yml
---
- name: Install traefik
  become: true
  hosts: traefik_server
  vars:
    force_recreate_containers: false
    # allow firewall for port 80 and 443
    firewall_default_protocol: tcp
    firewall_default_rule: allow
    firewall_services:
      - name: http
      - name: https
  roles:
    - role: traefik-docker/install
    - role: robertdebock.firewall
