  # meta:
  #   author: Sulochan Acharya
  #   description: This playbook will install a netmaker server using traefik as reverse proxy
  #   usage: ansible-playbook -i <inventory> /path/to/install-netmaker.yml
  #   refer to sample/group_vars/all.yml for parameters
---
- name: Install netmaker
  become: true
  hosts: netmaker_server
  gather_facts: true
  vars:
    nm_cert_resolver: dns
    force_recreate_containers: false
    firewall_services:
      - name: 51821
        protocol: udp
      - name: 51822
        protocol: udp
      - name: 51823
        protocol: udp
      - name: 51824
        protocol: udp
      - name: 51825
        protocol: udp
      - name: 51826
        protocol: udp
      - name: 51827
        protocol: udp
      - name: 51828
        protocol: udp
      - name: 51829
        protocol: udp
      - name: 51830
        protocol: udp
  roles:
    - role: netmaker-traefik-docker/install
    - role: robertdebock.firewall 
      tags: [all, allow-firewall]
