---
- name: Install adguard with docker
  gather_facts: true
  become: true
  hosts: adguard_server 
  vars:
    adguard_admin_user: admin
    adguard_admin_pw: $2a$12$0r5o5jTSUQd7LExuOX9LO.Iq6l15mx43NCVSR0f9DMHcCdgOfofy2
    adguard_dns_port: 53
    adguard_fqdn: dns.tickerwolf.com
    adguard_cert_resolver: dns
    adguard_image_version: v0.108.0-b.38
    adguard_traefik_network_name: traefik_tickernet_ansible_managed
    adguard_port_mappings:
      - '127.0.0.1:53:53/tcp'
      - '127.0.0.1:53:53/udp'
      # allow access from private network
      - '10.0.0.1:53:53/tcp'
      - '10.0.0.1:53:53/udp'

  roles:
    - role: adguard-docker/install
