---
- name: Adguard deploy docker-compose
  hosts: adguard_server
  gather_facts: true
  become: true
  vars:
    # adguard specific vars
    adguard_admin_user: admin
    adguard_admin_pw: $2a$12$0r5o5jTSUQd7LExuOX9LO.Iq6l15mx43NCVSR0f9DMHcCdgOfofy2
    adguard_dns_port: 53
    adguard_fqdn: dns.tickerwolf.com
    adguard_cert_resolver: dns
    adguard_image_version: v0.108.0-b.38
    adguard_traefik_network_name: traefik_tickernet_ansible_managed
    adguard_upstream_dns: https://dns.nextdns.io/4beb26
    adguard_port_mappings:
      - '127.0.0.1:53:53/tcp'
      - '127.0.0.1:53:53/udp'
      - '10.0.0.1:53:53/tcp'
      - '10.0.0.1:53:53/udp'
    # docker-compose-deploy specific vars
    docker_compose_template: "templates/docker-compose.yaml.j2"
    docker_compose_config_dir: /opt/ansible/docker-compose-apps/adguard
    force_recreate_containers: false
    remove_volumes: false
    additional_templates: 
      - "templates/AdGuardHome.yaml"
  roles:
    - role: docker-compose-deploy

  tasks:
    # need to allow DNS queries from docker network because ufw will block it by default
    - name: Allow DNS queries from docker network 
      community.general.ufw:
        rule: allow
        direction: in
        port: 53
        from_ip: 172.16.0.0/12

    - name: DELETE EXISTING RULE - Allow DNS queries from docker network 
      community.general.ufw:
        rule: allow
        direction: in
        port: 53
        from_ip: 172.16.0.0/12
        delete: true
      tags:
        - never 
        - down
        - uninstall
