---
- name: Promtail deploy docker-compose
  hosts: promtail_server
  gather_facts: true
  become: true
  vars:
    # promtail specific vars
    promtail_version: 2.8.3
    promtail_traefik_network_name: traefik_tickernet_ansible_managed
    promtail_loki_api_url: https://loki.acharya.cloud/loki/api/v1/push
    # docker-compose-deploy specific vars
    docker_compose_template: "templates/docker-compose.yaml.j2"
    docker_compose_config_dir: /opt/ansible/docker-compose-apps/promtail
    force_recreate_containers: false
    remove_volumes: false
    additional_templates: 
      - "templates/promtail.yaml"
  roles:
    - role: docker-compose-deploy