---
- name: Check netclient version
  shell: /usr/sbin/netclient version
  register: netclient_version
  changed_when: false
  failed_when: false

- name: Check if netclient version is already a desired version
  shell: /usr/sbin/netclient version | grep "{{ nc_version }}"
  register: netclient_version_check
  changed_when: false
  failed_when: false
  when: netclient_version.rc == 0

- name: Download and install netclient
  block:
    - name: Download netclient
      get_url:
        url: "https://fileserver.netmaker.io/releases/download/{{ nc_version }}/netclient-{{ nc_os_dist }}-{{ nc_arch }}"
        dest: "/usr/local/bin/netclient"
        mode: '0755'
        force: true
    - name: Stop netclient.service 
      systemd:
        name: netclient
        state: stopped
        enabled: yes
    - name: Install netclient
      command: /usr/local/bin/netclient install
      become: true
    - name: Start netclient.service 
      systemd:
        name: netclient
        state: started
        enabled: yes
  when: netclient_version_check.rc != 0
