---
- name: Check if netclient is installed
  shell: command -v /usr/sbin/netclient
  register: netclient_check
  failed_when: false
  changed_when: false

- name: Uninstall netclient if present
  command: /usr/sbin/netclient uninstall
  become: yes
  when: netclient_check.rc == 0

- name: Check if netclient.service exists
  stat: 
    path: /etc/systemd/system/netclient.service
  register: service_check

- name: Stop and disable netclient.service if present
  systemd:
    name: netclient
    state: stopped
    enabled: no
  when: service_check.stat.exists == true

- name: Delete netclient.service if present
  file:
    path: /etc/systemd/system/netclient.service
    state: absent
  become: yes
  when: service_check.stat.exists == true
...
