---
- name: Cadvisor deploy docker-compose
  hosts: docker_hosts
  gather_facts: true
  become: true
  vars:
    # cadvisor specific vars
    cadvisor_version: latest
    cadvisor_traefik_network_name: traefik_tickernet_ansible_managed
    cadvisor_cert_resolver: dns
    # docker-compose-deploy specific vars
    docker_compose_template: "templates/docker-compose.yaml.j2"
    docker_compose_config_dir: /opt/ansible/docker-compose-apps/cadvisor
    force_recreate_containers: false
    remove_volumes: false
  roles:
    - role: docker-compose-deploy