  # meta:
  #   author: Sulochan Acharya
  #   description: This playbook remove netmaker installation from provided hosts
  #   usage: ansible-playbook -i <inventory> /path/to/uninstall-netmaker.yml
---
- name: Uninstall traefik
  become: true
  hosts: netmaker_server
  vars:
    remove_volumes: false
    firewall_services:
      - name: 51821
        protocol: udp
        state: absent
      - name: 51822
        protocol: udp
        state: absent
      - name: 51823
        protocol: udp
        state: absent
      - name: 51824
        protocol: udp
        state: absent
      - name: 51825
        protocol: udp
        state: absent
      - name: 51826
        protocol: udp
        state: absent
      - name: 51827
        protocol: udp
        state: absent
      - name: 51828
        protocol: udp
        state: absent
      - name: 51829
        protocol: udp
        state: absent
      - name: 51830
        protocol: udp
        state: absent
  roles:
    - role: netmaker-traefik-docker/uninstall
    - role: robertdebock.firewall
