---
# Prerequisite: pre-configured cloud-init image named ubuntu-cloud should be ready!
- name: Create VM from cloud-init image 
  gather_facts: true 
  hosts: proxmox_hypervisor
  roles:
    - role: proxmox-vm-hypervisor
      vms:
        vldalstagsrv01:
          vmid: "101"
          clone: "ubuntu-cloud"
          cores: 4
          sockets: 1
          memory: 4096
          disksize: "15G"
          ipaddress0: "dhcp"
          gateway0: ""
          ipaddress1: "172.16.1.101/24"
          gateway1: "172.16.1.1"
        vldalstagsrv02:
          vmid: "102"
          clone: "ubuntu-cloud"
          cores: 4
          sockets: 1
          memory: 4096
          disksize: "15G"
          ipaddress0: "dhcp"
          gateway0: ""
          ipaddress1: "172.16.1.102/24"
          gateway1: "172.16.1.1"
        vldalstagsrv03:
          vmid: "103"
          clone: "ubuntu-cloud"
          cores: 4
          sockets: 1
          memory: 4096
          disksize: "15G"
          ipaddress0: "dhcp"
          gateway0: ""
          ipaddress1: "172.16.1.103/24"
          gateway1: "172.16.1.1"