---
# Prerequisite: pre-configured cloud-init image named ubuntu-cloud should be ready!
- name: Create VM from cloud-init image 
  gather_facts: true
  hosts: proxmox_hypervisor
  become: true
  roles:
    - role: proxmox-vm-hypervisor
      vms:
        vldalstagsrv01:
          node: "pldalprodsm01"
          vmid: "101"
          clone: "ubuntu-2404-cloudinit-template"
          cores: 4
          sockets: 1
          memory: 4096
          disksize: "15G"
          ciuser: "sulochan"
          cipassword: "changeme"
          bridge: "vmbr0"
          vlanid: 20
        vldalstagsrv02:
          node: "pldalprodsm01"
          vmid: "102"
          clone: "ubuntu-2404-cloudinit-template"
          cores: 4
          sockets: 1
          memory: 4096
          disksize: "15G"
          ciuser: "sulochan"
          cipassword: "changeme"
          bridge: "vmbr0"
          vlanid: 20
        vldalstagsrv03:
          node: "pldalprodsm01"
          vmid: "103"
          clone: "ubuntu-2404-cloudinit-template"
          cores: 4
          sockets: 1
          memory: 4096
          disksize: "15G"
          ciuser: "sulochan"
          cipassword: "changeme"
          bridge: "vmbr0"
          vlanid: 20
