---
- name: Get current hostname
  command: hostname
  register: current_hostname
  changed_when: false

- name: Set hostname
  become: yes
  hostname:
    name: "{{ hostname }}"
  when: hostname != current_hostname.stdout

- name: Reboot the host
  become: yes
  reboot:
    reboot_timeout: 600
  when: hostname != current_hostname.stdout

- name: Wait for host to be reachable
  wait_for_connection:
    timeout: 300
  when: hostname != current_hostname.stdout
...
