---
- name: Apt update and upgrade all packages
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Apt update
      apt:
        update_cache: yes
    - name: Apt upgrade
      apt:
        upgrade: yes
