  # meta:
  #   author: Sulochan Acharya
  #   description: This playbook will set hostname of servers to variable `hostname` for specified server
  #   usage: ansible-playbook -i <inventory> /path/to/set-hostname.yml
---
- name: Set hostname
  become: true
  gather_facts: true
  hosts: all
  vars:
    hostname: "{{ short_hostname }}"
    hostname_reboot: yes
  roles:
    - role: robertdebock.hostname
