---
- name: Set DNS servers
  hosts: all
  become: yes
  roles:
    - role: idiv_biodiversity.systemd_resolved
      systemd_resolved_servers:
        - "192.168.10.1"
        - "1.1.1.1"
      systemd_resolved_fallback_servers:
        - "8.8.8.8"
        - "8.8.4.4"
      systemd_resolved_domains:
        - "tickerwolf.com"