---
- name: Firewall Configuration
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Allow SSH
      community.general.ufw:
        rule: allow
        direction: in
        port: 22
