---
- name: Firewall Configuration
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Ensure UFW is reset
      community.general.ufw:
        state: reset
        
    - name: Ensure UFW is enabled and running
      community.general.ufw:
        state: enabled
        policy: deny
    
    - name: Start UFW and enable on boot
      service:
        name: ufw
        state: started
        enabled: true
        
    - name: Allow SSH from all private CIDR ranges
      community.general.ufw:
        rule: allow
        direction: in
        port: 22
        src: "{{ item }}"
      loop:
        - 100.64.0.0/10
        - 127.0.0.0/8
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
