---
- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: k3s-cluster/prereq
      become: true
    - role: k3s-cluster/download
      become: true

- hosts: k3s_master
  roles:
    - role: k3s-cluster/k3s/master
      become: true

- hosts: k3s_node
  roles:
    - role: k3s-cluster/k3s/node
      become: true