---
- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: k3s-cluster/reset
      become: true
  post_tasks:
    - name: Reboot and wait for node to come back up
      become: true
      reboot:
        reboot_timeout: 3600