---
  - name: Install node exporter
    gather_facts: true
    hosts: all
    become: yes
    vars:
      node_exporter_version: '1.6.0'
      node_exporter_arch: 'amd64' 
      node_exporter_host: '127.0.0.1'
      node_exporter_port: 9100
      node_exporter_state: started
      node_exporter_enabled: true
    roles:
      - role: geerlingguy.node_exporter
