---
- name: Deploy portainer agent
  hosts: portainer_agent_hosts
  become: true
  vars:
    portainer_listen_addr: "{{ ansible_tailscale0.ipv4.address }}:9001"
    portainer_agent_version: "2.20.3"
    portainer_agent_name: "portainer_agent"
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"

  tasks:
    - name: Deploy portainer agent container
      docker_container:
        name: "{{ portainer_agent_name }}"
        image: "portainer/agent:{{ portainer_agent_version }}"
        state: started
        restart_policy: always
        ports:
          - "{{ portainer_listen_addr }}:9001"
        volumes: "{{ docker_volumes }}"
        pull: true
