---
- name: Install Docker
  hosts: docker_hosts
  gather_facts: true
  become: true
  vars:
    docker_service_manage: true
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: true
    docker_compose_version: "v2.32.0"
    docker_compose_arch: "{{ ansible_architecture }}"
    docker_compose_path: /usr/bin/docker-compose
    docker_users:
      - ansible
      - sulochan
    docker_packages:
      - "docker-{{ docker_edition }}"
      - "docker-{{ docker_edition }}-cli"
      - "docker-{{ docker_edition }}-rootless-extras"
  roles:
    - geerlingguy.docker
