---
- name: Install golang
  gather_facts: true
  hosts: all
  become: yes
  vars:
    go_version: "1.20.5"
    go_platform: linux
    go_arch: amd64
    go_checksum: 'd7ec48cde0d3d2be2c69203bc3e0a44de8660b9c09a6e85c4732a3f7dc442612'
  roles:
    - geerlingguy.go
