---
- name: Install golang
  gather_facts: true
  hosts: all
  become: yes
  vars:
    go_version: "1.21.1"
    go_platform: linux
    go_arch: amd64
    go_checksum: 'b3075ae1ce5dab85f89bc7905d1632de23ca196bd8336afd93fa97434cfa55ae'
  roles:
    - geerlingguy.go
