global:
  checkNewVersion: true
  sendAnonymousUsage: false # true by default

log:
  level: {{ traefik_log_level }}

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

certificatesResolvers:
  http-staging:
    acme:
      email: {{ traefik_acme_http_email }}
      storage: /ssl-certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  
  dns-staging:
    acme:
      email: {{ traefik_acme_dns_email }}
      storage: /ssl-certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers: 
          - {{ traefik_acme_dns_resolver }}

  http:
    acme:
      email: {{ traefik_acme_http_email }}
      storage: /ssl-certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  dns:
    acme:
      email: {{ traefik_acme_dns_email }}
      storage: /ssl-certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers: 
          - {{ traefik_acme_dns_resolver }}

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

http:
  middlewares:
    public_svc:
      ipWhiteList:
        sourceRange:
          - "0.0.0.0/0"
    private_svc: 
      ipWhiteList:
        sourceRange:
          - "100.64.0.0/10"
          - "127.0.0.0/8"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"