---
- name: Harden Security
  become: true
  gather_facts: true
  hosts: all
  collections: 
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
    - robertdebock.fail2ban
  vars:
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
      os_auth_pw_max_age: 99999

