  # meta:
  #   author: Sulochan Acharya
  #   description: This playbook remove traefik installation from provided hosts
  #   usage: ansible-playbook -i <inventory> /path/to/uninstall-traefik.yml
---
- name: Uninstall traefik
  become: true
  hosts: traefik_server
  vars:
    remove_volumes: false
  roles:
    - role: traefik-docker/uninstall