---
# TODO: Work in progress
- name: Check if NVM is installed
  shell: command -v nvm
  register: nvm_check
  ignore_errors: yes

- name: Download and install NVM
  block:
    - name: Download NVM install script
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
        dest: /tmp/install_nvm.sh
        mode: '0755'
      when: nvm_check.rc != 0

- name: Ensure NVM directory exists
  file:
    path: /usr/local/nvm
    state: directory

- name: Run NVM install script with custom path
  shell: NVM_DIR="/usr/local/nvm" bash /tmp/install_nvm.sh
  args:
    creates: "/usr/local/nvm/nvm.sh"
  when: nvm_check.rc != 0

- name: Create NVM environment script in /etc/profile.d
  blockinfile:
    path: /etc/profile.d/nvm.sh
    create: yes
    block: |
      export NVM_DIR="/usr/local/nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  when: nvm_check.rc != 0
