version: '3.8'
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v2.10'
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
{% for port_mapping in traefik_port_mappings %}
      - {{ port_mapping }}  
{% endfor %}
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--global.checknewversion=true'
      - '--global.sendanonymoususage=false'
      - '--log.level=info'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.redirections.entryPoint.to=https'
      - '--entrypoints.http.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      - '--certificatesResolvers.http-staging.acme.email=sulochan.acharya2@gmail.com'
      - '--certificatesResolvers.http-staging.acme.storage=/traefik/acme.json'
      - '--certificatesResolvers.http-staging.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.http-staging.acme.httpChallenge.entryPoint=http'
      - '--certificatesResolvers.dns-staging.acme.email=sulochan.acharya2@gmail.com'
      - '--certificatesResolvers.dns-staging.acme.storage=/traefik/acme.json'
      - '--certificatesResolvers.dns-staging.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.dns-staging.acme.dnsChallenge.provider=cloudflare'
      - '--certificatesResolvers.dns-staging.acme.dnsChallenge.resolvers=1.1.1.1'
      - '--certificatesResolvers.http.acme.email=sulochan.acharya2@gmail.com'
      - '--certificatesResolvers.http.acme.storage=/traefik/acme.json'
      - '--certificatesResolvers.http.acme.caServer=https://acme-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.http.acme.httpChallenge.entryPoint=http'
      - '--certificatesResolvers.dns.acme.email=sulochan.acharya2@gmail.com'
      - '--certificatesResolvers.dns.acme.storage=/traefik/acme.json'
      - '--certificatesResolvers.dns.acme.caServer=https://acme-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.dns.acme.dnsChallenge.provider=cloudflare'
      - '--certificatesResolvers.dns.acme.dnsChallenge.resolvers=1.1.1.1'
      - '--certificatesResolvers.letsencrypt.acme.email=sulochan.acharya2@gmail.com'
      - '--certificatesResolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesResolvers.letsencrypt.acme.caServer=https://acme-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare'
      - '--certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'

    labels:
      - coolify.managed=true
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.middlewares.public_svc.ipwhitelist.sourcerange=0.0.0.0/0
      - traefik.http.middlewares.private_svc.ipwhitelist.sourcerange=100.64.0.0/10,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - traefik.http.middlewares.allow_from_cloudflare_and_local.ipwhitelist.sourcerange=127.0.0.0/8,100.64.0.0/10,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
