---
- name: N8N deploy docker-compose
  hosts: n8n_server
  gather_facts: true
  become: true
  vars:
    # n8n specific vars
    n8n_version: 1.1.1
    n8n_fqdn: n8n.tickerwolf.com
    n8n_cert_resolver: dns
    n8n_traefik_network_name: traefik_tickernet_ansible_managed
    # docker-compose-deploy specific vars
    docker_compose_template: "templates/docker-compose.yaml.j2"
    docker_compose_config_dir: /opt/ansible/docker-compose-apps/n8n
    force_recreate_containers: false
    remove_volumes: false
  roles:
    - role: docker-compose-deploy