---
- name: Check environment variable for cloudflare api key
  fail:
    msg: "Environment variable CLOUDFLARE_DNS_API_TOKEN is not defined or empty"
  when: lookup('env', 'CLOUDFLARE_DNS_API_TOKEN') == ''

- name: Set cloudflare api key from environment variable
  set_fact:
    cloudflare_dns_api_token: "{{ lookup('env', 'CLOUDFLARE_DNS_API_TOKEN') }}"
  failed_when: cloudflare_dns_api_token is not defined

- name: Verify docker installation
  service:
    name: docker
    state: started
    enabled: yes

- name: Get docker-compose version 
  command: docker-compose --version 
  register: docker_compose_version_result 
  changed_when: false 
  ignore_errors: true

- name: Parse docker-compose version 
  set_fact:
    docker_compose_version: " {{ docker_compose_version_result.stdout | regex_search('(\\d+)') | first | trim }} "
  when: docker_compose_version_result is success

- name: Assert docker-compose major version is 2
  assert:
    that: 
      - docker_compose_version == ' 2 '
    fail_msg: "The installed docker-compose version ({{ docker_compose_version }}) is not 2.x"
  when: docker_compose_version_result is success 


- name: Create directories for Traefik configuration
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/traefik
    - /ssl-certs

- name: Copy traefik configuration file
  template:
    src: "traefik.yaml.j2"
    dest: /etc/traefik/traefik.yaml
  
- name: Copy docker-compose file
  template:
    src: "docker-compose.yaml.j2"
    dest: /etc/traefik/docker-compose.yaml

- name: Start traefik container
  shell: docker-compose up -d{{' --force-recreate' if force_recreate_containers else ''}}
  args:
    chdir: /etc/traefik
  tags: traefik
  environment:
    CLOUDFLARE_DNS_API_TOKEN: "{{ cloudflare_dns_api_token }}"
